#################################################################################################
# 修改 TNAME: R2100 中的R2100为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
# 小米AC2100型号为R2100
# 红米AC2100型号为RM2100
#################################################################################################
name: Build Padavan zerotier 6

on:
  repository_dispatch:
    types: [lean, x86_64]
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *
  watch:
    types: started

env:                      # 环境变量
  MHZ: 1000               # CPU超频频率 必须为20的倍数。开启超频请修改124行超频选项
  TNAME: PSG1218_nano           # 配置文件名  https://github.com/hanwckf/rt-n56u/tree/master/trunk/configs/templates
  BUILD_VERSION: xumng123  # hanwckf 或者 chongshengB

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo timedatectl set-timezone "Asia/Shanghai"
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/$BUILD_VERSION/rt-n56u.git /opt/rt-n56u
        sudo sed -i 's|https://gomirrors.org/dl/go/go$(go_version).linux-amd64.tar.gz|https://codeload.github.com/golang/go/tar.gz/go$(go_version)|g' /opt/rt-n56u/trunk/tools/Makefile       
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - id: vars
      run: |
        echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo sed -i 's|SYS_USER_ROOT		"admin"|SYS_USER_ROOT		"root"|g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sudo sed -i 's|DEF_ROOT_PASSWORD	"admin"|DEF_ROOT_PASSWORD	"5234581"|g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sudo sed -i 's|192.168.2|192.168.6|g' /opt/rt-n56u/trunk/user/shared/defaults.h
        #sudo sed -i 's|BOARD_PID "_%s"|BOARD_PID "RBT"|g' /opt/rt-n56u/trunk/user/shared/defaults.h
        #sudo sed -i 's|BOARD_PID "_5G_%s"|BOARD_PID "RBT_5G"|g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sudo sed -i 's|1234567890|asdfghjkl|g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sudo sed -i 's|$(nvram get zerotier_secret)|3e3270acfd:0:86cad609513028f9646d1ad560ac7b116ada4618f8e37bcad8d94e31e36a7f3329fa6a910b199a920277b2c2ec5eed7262d8c3cd2696e1e10e863e16f5336a4d:dd68b91458eac769c75dfce7e11bad3064ce4cb632c378c2438a7585ab61271325ead23c7036ee1d6e2894ccc38f8522d337aaab990ae904220e3ba1f5f71b7d|g' /opt/rt-n56u/trunk/user/zerotier/zerotier.sh
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' configs/templates/$TNAME.config
        ###################################################################################################
        # 因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ###################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LANG_UK/d' configs/templates/$TNAME.config      #删除配置项英文界面
        sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS/d' configs/templates/$TNAME.config          #删除配置项QOS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' configs/templates/$TNAME.config       #删除配置项SMBD36
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DDNS_SSL/d' configs/templates/$TNAME.config     #删除配置项DDNS_SSL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTTPS/d' configs/templates/$TNAME.config        #删除配置项HTTPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' configs/templates/$TNAME.config      #删除配置项OPENVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' configs/templates/$TNAME.config   #删除配置项FFMPEG_NEW
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' configs/templates/$TNAME.config       #删除配置项XUPNPD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' configs/templates/$TNAME.config       #删除配置项DOGCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' configs/templates/$TNAME.config  #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' configs/templates/$TNAME.config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' configs/templates/$TNAME.config       #删除配置项VLMCSD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' configs/templates/$TNAME.config         #删除配置项TTYD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' configs/templates/$TNAME.config       #删除配置项NAPT66
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' configs/templates/$TNAME.config       #删除配置项SRELAY
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' configs/templates/$TNAME.config        #删除配置项SOCAT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' configs/templates/$TNAME.config          #删除配置项MTR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' configs/templates/$TNAME.config       #删除配置项IPERF3
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' configs/templates/$TNAME.config         #删除配置项NANO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' configs/templates/$TNAME.config         #删除配置项HTOP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' configs/templates/$TNAME.config        #删除配置项LRZSZ
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' configs/templates/$TNAME.config         #删除配置项CURL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' configs/templates/$TNAME.config      #删除配置项OPENSSH
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' configs/templates/$TNAME.config         #删除配置项SFTP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' configs/templates/$TNAME.config      #删除配置项TCPDUMP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' configs/templates/$TNAME.config     #删除配置项EAP_PEAP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC/d' configs/templates/$TNAME.config   #删除配置项OPENSSL_EC
        sed -i '/CONFIG_FIRMWARE_CPU_900MHZ/d' configs/templates/$TNAME.config           #删除配置项超频900MHz
        
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' configs/templates/$TNAME.config  #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' configs/templates/$TNAME.config  #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' configs/templates/$TNAME.config  #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' configs/templates/$TNAME.config  #删除配置项SS plus+
        ####################################################################
        # 以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件。
        ####################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_LANG_CN=y" >> configs/templates/$TNAME.config      #设置界面简体中文
        echo "CONFIG_FIRMWARE_INCLUDE_QOS=n" >> configs/templates/$TNAME.config          #删除QOS
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD36=n" >> configs/templates/$TNAME.config       #使用SMBD36新版本
        echo "CONFIG_FIRMWARE_INCLUDE_DDNS_SSL=n" >> configs/templates/$TNAME.config     #删除DDNS_SSL
        echo "CONFIG_FIRMWARE_INCLUDE_HTTPS=n" >> configs/templates/$TNAME.config        #删除HTTPS
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> configs/templates/$TNAME.config      #删除OPENVPN
        echo "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> configs/templates/$TNAME.config   #使用FFMPEG新版本
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> configs/templates/$TNAME.config       #删除用于IPTV的XUPNPD
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> configs/templates/$TNAME.config       #删除用于Drcom的工具DOGCOM
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> configs/templates/$TNAME.config  #删除SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> configs/templates/$TNAME.config #删除DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> configs/templates/$TNAME.config       #删除用于KMS的工具VLMCSD
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> configs/templates/$TNAME.config         #删除网页终端模拟器TTYD
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> configs/templates/$TNAME.config       #删除用于二级路由、教育网分发IPv6地址的NAPT66
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> configs/templates/$TNAME.config       #删除SRELAY
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> configs/templates/$TNAME.config        #删除工具SOCAT
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> configs/templates/$TNAME.config          #删除工具MTR
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> configs/templates/$TNAME.config       #删除工具IPERF3
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> configs/templates/$TNAME.config         #删除工具NANO
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> configs/templates/$TNAME.config         #删除工具HTOP
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> configs/templates/$TNAME.config        #删除工具LRZSZ
        echo "CONFIG_FIRMWARE_INCLUDE_CURL=y" >> configs/templates/$TNAME.config         #删除工具CURL
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> configs/templates/$TNAME.config      #删除OPENSSH
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n" >> configs/templates/$TNAME.config         #删除SFTP
        echo "CONFIG_FIRMWARE_INCLUDE_TCPDUMP=n" >> configs/templates/$TNAME.config      #删除TCPDUMP
        echo "CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=n" >> configs/templates/$TNAME.config     #删除EAP_PEAP
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC=y" >> configs/templates/$TNAME.config   #删除OPENSSL_EC
        echo "CONFIG_FIRMWARE_ENABLE_IPV6=y" >> configs/templates/$TNAME.config
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> configs/templates/$TNAME.config
        echo "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> configs/templates/$TNAME.config
        #########################################################################################
        # 自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        # https://github.com/hanwckf/rt-n56u/blob/master/trunk/configs/templates/
        # 格式如下：
        # sed -i '/自定义项/d' configs/templates/$TNAME.config
        # echo "自定义项=y" >> configs/templates/$TNAME.config
        
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' configs/templates/$TNAME.config         #测试样例
        echo "CONFIG_FIRMWARE_INCLUDE_FTPD=n" >> configs/templates/$TNAME.config         #测试样例
        
        #########################################################################################
        # 以下插件为 chongshengB 版本专属插件，hanwckf 版不可用!!!
        # 如需使用这些插件，请修改24行 BUILD_VERSION 为 chongshengB
        #########################################################################################
        if [ $BUILD_VERSION == "xumng123" ]; then
          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> configs/templates/$TNAME.config      #simple-obfs混淆插件
          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> configs/templates/$TNAME.config      #adbyby plus+
          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> configs/templates/$TNAME.config     #阿里DDNS
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> configs/templates/$TNAME.config    #smartdns
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> configs/templates/$TNAME.config #smartdns二进制文件
          # 特别注意，开启v2同样需要开启113行的shadowsocks，否则不会编译
          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> configs/templates/$TNAME.config       #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> configs/templates/$TNAME.config      #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> configs/templates/$TNAME.config   #KP广告过滤
          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> configs/templates/$TNAME.config       #在线文件管理服务
          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> configs/templates/$TNAME.config    #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> configs/templates/$TNAME.config #集成AdGuardHome
          echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> configs/templates/$TNAME.config         #网易云解锁
          echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> configs/templates/$TNAME.config      #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> configs/templates/$TNAME.config    #zerotier ~1.3M
          echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=n" >> configs/templates/$TNAME.config
          echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=n" >> configs/templates/$TNAME.config
          echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> configs/templates/$TNAME.config
        fi
        #########################################################################################
        sudo ./clear_tree
        cp -f configs/templates/$TNAME.config .config
        sudo fakeroot ./build_firmware_modify $TNAME 0
        #sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
        #cp .config /opt/images/test.config
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan_K2-6.0${{ env.FILE_DATE }}
        path: /opt/images
